import fs from 'node:fs';
import path from 'node:path';

const marker = '<!-- arqboard-coverage-report -->';
const root = process.cwd();
const outputDir = path.join(root, 'coverage');

function readGoCoverage() {
  const summaryPath = path.join(outputDir, 'go-summary.txt');
  const text = readText(summaryPath);
  const totalLine = text
    .split(/\r?\n/)
    .find((line) => line.trim().startsWith('total:'));

  if (!totalLine) {
    return 'n/a';
  }

  return totalLine.match(/([\d.]+%)/)?.[1] ?? 'n/a';
}

function readWebCoverage() {
  const summaryPath = path.join(root, 'web', 'coverage', 'coverage-summary.json');
  const summary = JSON.parse(readText(summaryPath));
  const total = summary.total;

  return {
    lines: formatPct(total.lines.pct),
    statements: formatPct(total.statements.pct),
    functions: formatPct(total.functions.pct),
    branches: formatPct(total.branches.pct),
  };
}

function formatPct(value) {
  if (typeof value !== 'number') {
    return 'n/a';
  }
  return `${value.toFixed(1)}%`;
}

function readText(filePath) {
  const buffer = fs.readFileSync(filePath);
  const utf8 = buffer.toString('utf8');
  if (utf8.includes('\u0000')) {
    return buffer.toString('utf16le');
  }
  return utf8;
}

fs.mkdirSync(outputDir, { recursive: true });

const goCoverage = readGoCoverage();
const webCoverage = readWebCoverage();

const body = `${marker}
## Test Coverage

| Suite | Metric | Coverage |
| --- | --- | ---: |
| Go | statements | ${goCoverage} |
| Web | lines | ${webCoverage.lines} |
| Web | statements | ${webCoverage.statements} |
| Web | functions | ${webCoverage.functions} |
| Web | branches | ${webCoverage.branches} |

Generated by the \`ci\` workflow for this PR.
`;

fs.writeFileSync(path.join(outputDir, 'coverage-comment.md'), body);

if (process.env.GITHUB_STEP_SUMMARY) {
  fs.appendFileSync(
    process.env.GITHUB_STEP_SUMMARY,
    body.replace(`${marker}\n`, '')
  );
}

console.log(body);
